version: "3.4"

networks:
  budgeteer-network:
    driver: bridge

services:
  budgeteer-api:
    image: budgeteer-api
    build:
      context: ./Budgeteer.API
      dockerfile: ./Dockerfile
    container_name: budgeteer-api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:7069/
    ports:
      - 7069:8080
    networks:
      - budgeteer-network

  budgeteer-frontend:
    image: budgeteer-frontend
    build:
      context: ./Budgeteer.UI
      dockerfile: ./Dockerfile
    container_name: budgeteer-frontend
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - budgeteer-network
    depends_on:
      - budgeteer-api
    volumes:
      - ./Budgeteer.UI:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    name: node-modules
