version: "3.4"

networks:
  budgeteer-network:
    driver: bridge

services:
  budgeteer-api:
    image: budgeteer-api
    build:
      context: ./Budgeteer.API
      dockerfile: ./Dockerfile
    container_name: budgeteer-api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:7069/
    ports:
      - 7069:8080
    networks:
      - budgeteer-network
    depends_on:
      - sqlserver

  budgeteer-frontend:
    image: budgeteer-frontend
    build:
      context: ./Budgeteer.UI
      dockerfile: ./Dockerfile
    container_name: budgeteer-frontend
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - budgeteer-network
    depends_on:
      - budgeteer-api
    volumes:
      - ./Budgeteer.UI:/app
      - node_modules:/app/node_modules

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest # if working on Windows
    #image: mcr.microsoft.com/azure-sql-edge:latest # if working on MAC arm64
    user: root
    environment:
      - "MSSQL_SA_PASSWORD=yourStrong($$)Password"
      - "ACCEPT_EULA=Y"
    container_name: sqlserver
    ports:
      - 1433:1433
    networks:
      - budgeteer-network
    volumes:
      - dbdata:/var/opt/mssql/data

volumes:
  dbdata:
    name: sqlserver
  node_modules:
    name: node-modules
